# Generated by Django 5.1.7 on 2025-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='scan_image',
            field=models.ImageField(blank=True, null=True, upload_to='scan_images/'),
        ),
    ]
